import app from './worker-entry.mjs';

function withDashboardClient(html='') {
  const stripped = String(html).replace(/<script>[\s\S]*?<\/script>/i, '');
  const css=`<style>.manualSite{background:#10141a;border:1px solid #27303b;border-radius:24px;padding:18px;margin:0 0 24px}.manualSite h3{font-size:22px;margin:0 0 5px}.manualSite p{color:#9da6b1;margin:0 0 14px;line-height:1.5}.manualGrid{display:grid;grid-template-columns:2fr 1fr;gap:9px}.manualGrid input{width:100%;min-width:0;background:#fff;color:#111;border:0;border-radius:13px;padding:14px;font:inherit}.manualGrid button{grid-column:1/-1;border:0;border-radius:13px;padding:14px;background:#dfff48;color:#111;font-weight:950;font-size:16px}.manualStatus{min-height:20px;margin-top:10px;color:#adb5bf;font-size:13px}.manualStatus a{color:#dfff48;font-weight:850}@media(max-width:700px){.manualGrid{grid-template-columns:1fr}.manualGrid>*{grid-column:1/-1}}</style>`;
  const manual=`<section class="manualSite"><h3>Add my own website</h3><p>Already have a site or a specific business in mind? Paste the URL and Revenue Hunter will run the same audit, collect its information and images, build a dossier and create a demo.</p><form id="manualForm" class="manualGrid"><input id="manualWebsite" inputmode="url" placeholder="Website URL — e.g. mybusiness.co.uk" required><input id="manualName" placeholder="Business name (optional)"><input id="manualCategory" placeholder="Business type (optional)"><input id="manualLocation" placeholder="Location (optional)"><button id="manualBtn" type="button">Analyse my website</button></form><div id="manualStatus" class="manualStatus"></div></section>`;
  return stripped.replace('</head>',css+'</head>').replace('<div id="summary" class="summary">',manual+'<div id="summary" class="summary">').replace('</body>', '<script src="/dashboard-client.js?v=5" defer></script></body>');
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    if (url.pathname === '/dashboard-client.js' && request.method === 'GET') {
      return new Response(`(()=>{'use strict';${DASHBOARD_CLIENT_SOURCE}})();`, {headers:{'content-type':'application/javascript; charset=utf-8','cache-control':'public, max-age=60'}});
    }
    const response = await app.fetch(request, env, ctx);
    if (url.pathname === '/' && request.method === 'GET' && response.headers.get('content-type')?.includes('text/html')) {
      const html = await response.text();
      const headers = new Headers(response.headers); headers.set('content-type','text/html; charset=utf-8'); headers.set('cache-control','no-store');
      return new Response(withDashboardClient(html), {status:response.status,headers});
    }
    return response;
  },
  scheduled(controller, env, ctx) { return app.scheduled?.(controller, env, ctx); }
};

const DASHBOARD_CLIENT_SOURCE = `
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const pj=v=>{try{return JSON.parse(v||'{}')}catch{return{}}};const money=n=>Number.isFinite(Number(n))?'£'+Math.round(Number(n)).toLocaleString('en-GB'):'—';const savedOnly=new URLSearchParams(location.search).get('view')==='saved';async function jf(url,o){const r=await fetch(url,o),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||('HTTP '+r.status));return b}
function contacts(x,c){const ph=(c.phones&&c.phones[0])||c.phone||x.phone||'',em=(c.emails&&c.emails[0])||c.email||'';let h=ph?'<a href="tel:'+esc(ph)+'">☎ '+esc(ph)+'</a>':'<span class="muted">Phone not found</span>';if(em)h+='<a href="mailto:'+esc(em)+'">✉ '+esc(em)+'</a>';if(x.website)h+='<a href="'+esc(x.website)+'" target="_blank" rel="noreferrer">↗ '+esc(x.website)+'</a>';return h}
function card(x){const ev=pj(x.evidence_json),c=ev.contacts||{},br=pj(x.brand_json),logo=br.logoUrl||br.faviconUrl||'',verified=x.company_number?'<span class="badge verified">Companies House '+esc(x.company_status||'matched')+'</span>':'<span class="badge">Identity '+esc(Math.round(x.identity_confidence||0))+'%</span>',score=x.score?Math.round(x.score):'—',eff=x.expected_effort_minutes?(Math.round((x.expected_effort_minutes/60)*10)/10)+'h':'—',sv=Boolean(x.saved);return '<article class="card"><div class="cardTop"><div><div class="name">'+esc(x.name)+'</div><div class="muted">'+esc(x.category||'business')+' • '+esc(x.address||'')+'</div>'+verified+'<span class="badge">'+esc(x.sales_stage||'new')+'</span>'+(logo?'<br><img class="brandThumb" src="'+esc(logo)+'" alt="">':'')+'</div><div class="score">'+esc(score)+'</div></div><div class="problem">'+esc(x.primary_problem||'Awaiting investigation')+'</div><div class="muted">'+esc(x.proposed_solution||'')+'</div><div class="why"><b>WHY THIS COULD MAKE MONEY</b><br>'+esc(ev.whyChosen||'Evidence still being built.')+'</div><div class="contact">'+contacts(x,c)+'</div><div class="economics"><div><small>Offer</small><br><b>'+money(x.offer_price)+'</b></div><div><small>Margin</small><br><b>'+money(x.expected_margin)+'</b></div><div><small>Effort</small><br><b>'+esc(eff)+'</b></div></div><div class="actions"><a href="/demo/'+encodeURIComponent(x.id)+'">Demo</a><a href="/dossier/'+encodeURIComponent(x.id)+'">Dossier</a><a href="/evidence/'+encodeURIComponent(x.id)+'">Evidence</a><button type="button" class="saveBtn '+(sv?'saved':'')+'" data-save-id="'+esc(x.id)+'" data-save-next="'+(sv?'0':'1')+'">'+(sv?'★ Saved':'☆ Save')+'</button></div></article>'}
async function load(){const a=await Promise.all([jf('/api/dashboard'),jf('/api/prospects?limit=60'+(savedOnly?'&saved=1':''))]),d=a[0],ps=a[1],t=d.totals||{};$('#summary').innerHTML=[['Prospects',t.prospects||0],['★ Saved',t.saved||0],['80+ score',t.high_value||0],['Indicative margin',money(t.indicative_margin||0)]].map(x=>'<div class="sum"><small>'+esc(x[0])+'</small><strong>'+esc(x[1])+'</strong></div>').join('');$('#heading').textContent=savedOnly?'★ Saved prospects':'Prospects';$('#count').textContent=ps.length+' shown';$('#cards').innerHTML=ps.length?ps.map(card).join(''):'<div class="muted">No prospects in this view yet.</div>'}
async function save(btn){const id=btn.dataset.saveId,sv=btn.dataset.saveNext==='1';btn.disabled=true;try{await jf('/api/prospects/'+encodeURIComponent(id)+'/save',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({saved:sv})});await load()}finally{btn.disabled=false}}
async function run(){const q=$('#q').value.trim(),btn=$('#huntBtn'),st=$('#status');if(!q||btn.disabled)return;btn.disabled=true;btn.textContent='Hunting…';let s=0;st.innerHTML='<span class="spinner"></span>Starting Revenue Hunter…';const tm=setInterval(()=>{s++;st.innerHTML='<span class="spinner"></span>Revenue Hunter is working — '+s+'s. Results are saved as they complete.'},1000);try{const d=await jf('/api/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:q})});st.textContent='Run complete — '+(d.count||0)+' processed.';await load()}catch(e){st.textContent='Run paused: '+e.message+'. Completed prospects are already saved.';await load().catch(()=>{})}finally{clearInterval(tm);btn.disabled=false;btn.textContent='Hunt opportunities'}}
async function manual(){const web=$('#manualWebsite').value.trim(),btn=$('#manualBtn'),st=$('#manualStatus');if(!web||btn.disabled)return;btn.disabled=true;btn.textContent='Analysing…';let s=0;st.innerHTML='<span class="spinner"></span>Reading the website and building its dossier…';const tm=setInterval(()=>{s++;st.innerHTML='<span class="spinner"></span>Auditing website — '+s+'s. Collecting services, images, contacts and opportunities…'},1000);try{const d=await jf('/api/manual-site',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({website:web,name:$('#manualName').value.trim(),category:$('#manualCategory').value.trim(),location:$('#manualLocation').value.trim()})});st.innerHTML='Done. <a href="'+esc(d.dossier)+'">Open dossier</a> · <a href="'+esc(d.demo)+'">Open demo</a>';await load()}catch(e){st.textContent='Could not analyse website: '+e.message}finally{clearInterval(tm);btn.disabled=false;btn.textContent='Analyse my website'}}
function init(){const f=$('#hunt'),b=$('#huntBtn');if(!f||!b)return;f.action='javascript:void(0)';f.addEventListener('submit',e=>{e.preventDefault();run()});b.type='button';b.addEventListener('click',run);const mf=$('#manualForm'),mb=$('#manualBtn');if(mf&&mb){mf.action='javascript:void(0)';mf.addEventListener('submit',e=>{e.preventDefault();manual()});mb.type='button';mb.addEventListener('click',manual)}$('#cards').addEventListener('click',e=>{const s=e.target.closest('[data-save-id]');if(s)save(s)});load().catch(e=>{$('#status').textContent='Dashboard data could not load: '+e.message})}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
`;